### ISSUE TITLE
Doesn't work with plank make [BUG]

### ISSUE THREAD

**Issue by Moonbed1994** [guillaume009/runelite-plugin-action-progress#58] opened 2024-03-29 21:08 UTC
**Describe the bug**
The action progress bar does not appear when do the plank malke spell. 

**To Reproduce**
For me all I have too do is initiate the plank make spell. 

**Expected behavior**
I expect the progress bar to appear. 

I've attempted to turn plugin on and off, uninstall/reinstall plugin, update windows, update runelite, restart pc but doesnt seem to help. All other skills seem to work though just not plank make. 

![Screenshot 1](https://github.com/guillaume009/runelite-plugin-action-progress/assets/165427852/e1e78089-fe02-486c-b6bd-307c1ceff2f6)
![Screenshot 2](https://github.com/guillaume009/runelite-plugin-action-progress/assets/165427852/5fd583ca-756b-4269-a9d5-d75253a0f237)

**Comment by guillaume009** [comment] 2024-04-06 22:17
@Moonbed1994 I have taken a look and I don't see anything wrong at first glance in the code. To help me figure it out, does the string jewellery spell make the bar appear? Interested to know since it's in the same spellbook.

Unfortunately I don't have the magic lvl to try the plank make spell, so your help will be needed for that

**Comment by liniim** [comment] 2024-04-08 14:36
String Jewellery works, Plank Make doesnt.

**Comment by Moonbed1994** [comment] 2024-04-14 11:58
@guillaume009 as above, the progress bar will appear when using a plank on a log but of couse the action will stop.

**Comment by Moonbed1994** [comment] 2024-04-14 12:11
I'd like to add that previously it has been working correctly but only in the last couple of weeks it has broken.

**Comment by guillaume009** [comment] 2024-04-14 15:39
The magic spells were modified recently to combine the enchant spells into a new sub menu. I was thinking that this might explain why plank make doesn't work, because the code looks for the index of the spell in the list to execute the corresponding logic. However, it was confirmed that string jewellery works. This likely means that the issue is not there.

I am able to reproduce the problem of the action bar showing when a plank is double clicked or when one plank is clicked with another. This is a different problem than the fact that casting the spell doesn't trigger the action bar. If anything, the bar showing when clicking plank is a good sign, because it means the check for the requirements of the spell (runes + money) works.

Can you try looking at the runelite logs to see if there are any exception when casting plank make related to this plugin that could help me figure out where the issue is? You can access them here :

%userprofile%\.runelite\logs

Here is an example of the debug logs when running the plugin locally. Those will not be available in the released version, but it should give you an idea 

![image](https://github.com/guillaume009/runelite-plugin-action-progress/assets/8568544/bc7e2cc8-85c3-46a2-9580-588cbf6c2e15)

**Comment by guillaume009** [comment] 2024-04-20 12:22
@druyang Can you make a different bug for that? It's a different problem

**Comment by guillaume009** [comment] 2024-04-20 16:21
Yes, the two things are unrelated.

One can be fixed without the other being fixed

**Comment by guillaume009** [comment] 2024-04-27 15:00
Will be merged on runelite here 

https://github.com/runelite/plugin-hub/pull/5944

**Closed by guillaume009** 2024-04-27 15:00 UTC
