### ISSUE TITLE
Smithing does not bring up progress bar

### ISSUE THREAD

**Issue by 4GotMyName** [guillaume009/runelite-plugin-action-progress#8] opened 2023-06-05 18:13 UTC
Smithing mithril darts at Varrock anvils does not seem to bring up the progress bar.

**To Reproduce**
Gear: Full Smiths outfit, Imcando hammer, Graceful head and cape.
Banked all gear and put regular hammer into invent just to test, but did not fix
27-28 bars in invent, and will not track smithing. 
Tested fletching and herb and works as expected.

**Comment by guillaume009** [comment] 2023-06-06 01:02
I am aware of this issue. I need to learn more about how events work in runescape to execute code when the spacebar is pressed. If you manually click the item you want to smith, it should show the progress bar

**Comment by 4GotMyName** [comment] 2023-06-06 01:20
Hey, just as a heads up (obviously I'm using Runelite) but that is with me clicking on the dart tips. I was oddly unaware and feel like I have given myself a lot of wrist pain as a result... that I could press space bar bahaha.

I'll play around with it more tomorrow and let you know if I find a change or setting that makes it work. Btw the plug is awesome so far for everything else I have tried it on.

Not really sure what it could be, but I enjoy smashing my head against the keyboard / brute forcing random variables / changes until something works. (I mean that in the most sincere way, it is actually fun to me)

Thanks for the fast response,
Hopefully, I can via a little trial and error, find something or combo that works.

-4GotMyName

**Comment by Jemades** [comment] 2023-09-12 03:27
Any update on this?

You can get the progress bar to appear for one inventory if you smith something else and then go back to darts. But if you try to do a second inventory (either by spacebar or clicking darts icon), the progress bar stops appearing.

**Comment by guillaume009** [comment] 2023-09-12 22:56
Sorry, no new update, I haven't gotten around to do it. Like I said above, the issue is when the spacebar is used to select what to smith. If you click it everything should work properly.

**Comment by guillaume009** [comment] 2023-09-16 20:54
It took a while but I got help to fix this issue and have a PR opened on the RuneLite hub. It has been taking a bit of time recently to get things merged, but I'll close this issue once it is.

**Closed** 2023-10-16 00:49 UTC
